
export const MORSE_CODE_MAP = {
  'A': '.-', 'B': '-...', 'C': '-.-.', 'D': '-..', 'E': '.', 'F': '..-.', 'G': '--.', 'H': '....', 'I': '..', 'J': '.---',
  'K': '-.-', 'L': '.-..', 'M': '--', 'N': '-.', 'O': '---', 'P': '.--.', 'Q': '--.-', 'R': '.-.', 'S': '...', 'T': '-',
  'U': '..-', 'V': '...-', 'W': '.--', 'X': '-..-', 'Y': '-.--', 'Z': '--..',
  '1': '.----', '2': '..---', '3': '...--', '4': '....-', '5': '.....', '6': '-....', '7': '--...', '8': '---..', '9': '----.', '0': '-----',
  '.': '.-.-.-', ',': '--..--', '?': '..--..', "'": '.----.', '!': '-.-.--', '/': '-..-.', '(': '-.--.', ')': '-.--.-',
  '&': '.-...', ':': '---...', ';': '-.-.-.', '=': '-...-', '+': '.-.-.', '-': '-....-', '_': '..--.-', '"': '.-..-.',
  '$': '...-..-', '@': '.--.-.'
};

export const MORSE_PROSIGNS_MAP = {
    'AR': { name: 'End of Message', morse: '.-.-.' },
    'AS': { name: 'Wait', morse: '.-...' },
    'BT': { name: 'Separator', morse: '-...-' },
    'CL': { name: 'Closing Down', morse: '-.-..-..' },
    'CQ': { name: 'Calling Any Station', morse: '-.-.--.-' },
    'KA': { name: 'Start of Message', morse: '-.-.-' },
    'KN': { name: 'Invite Specific Station', morse: '-.--.' },
    'SK': { name: 'End of Contact', morse: '...-.-' },
    'SN': { name: 'Understood', morse: '...-.' },
};

export const PRACTICE_WORDS = [
    "ABOUT", "AGAIN", "BELOW", "COULD", "EVERY", "FIRST", "FOUND", "GREAT", "HOUSE", "LARGE", "LEARN", "NEVER", "OTHER", "PLACE", "PLANT", "POINT", "RIGHT", "SMALL", "SOUND", "SPELL", "STILL", "STUDY", "THEIR", "THERE", "THESE", "THING", "THINK", "THREE", "WATER", "WHERE", "WHICH", "WORLD", "WOULD", "WRITE",
    "ZERO", "ONE", "TWO", "FOUR", "FIVE", "SIX", "SEVEN", "EIGHT", "NINE", "TEN", "CQ", "73", "DX", "RADIO", "SIGNAL"
];

export const MORSE_CODE_FUN_FACTS = [
    "The first-ever public telegraph message, 'What hath God wrought', was sent by Samuel Morse in 1844.",
    "The famous SOS distress signal (... --- ...) doesn't stand for 'Save Our Souls'. It was chosen for its simple, unmistakable pattern.",
    "Morse code can be transmitted using sound, light, or even by tapping fingers.",
    "The spaces between letters and words are just as important as the dots and dashes for clear communication.",
    "The speed of Morse code is measured in Words Per Minute (WPM).",
    "The letter 'E', a single dot, is the most common letter in English, so it has the shortest code.",
    "Conversely, 'Q' (--.-) and 'Z' (--..) are less common and have longer codes.",
    "Alfred Vail was Samuel Morse's partner and made significant contributions to the code's development.",
    "Before SOS, the distress signal was 'CQD', which meant 'Calling All Stations - Distress'.",
    "In amateur radio, Morse code is often called 'CW', which stands for Continuous Wave.",
    "The Farnsworth method helps beginners learn by sending characters at a high speed but with long pauses between them.",
    "Morse code was vital for communication during World War I and World War II.",
    "The Titanic sent out distress calls in Morse code after hitting an iceberg in 1912.",
    "A dot (or 'dit') is the basic unit of time in Morse code.",
    "A dash (or 'dah') is three times as long as a dot.",
    "The space between dots and dashes within a character is one dot long.",
    "The space between letters is three dots long.",
    "The space between words is seven dots long.",
    "Morse code is a binary system, using only two states: on (signal) and off (silence).",
    "The world record for Morse code speed is over 75 WPM, held by Ted McElroy.",
    "Prisoners of war have used Morse code by tapping on pipes or walls to communicate.",
    "The Nokia tune, a famous ringtone, is Morse code for 'SMS' (... -- ...).",
    "Pilots use Morse code to identify navigational beacons, which transmit their identifiers as a series of dits and dahs.",
    "The ampersand (&) in Morse code (.-...) sounds like 'ES', a common abbreviation for 'and'.",
    "Some people can 'copy' Morse code in their head without writing it down.",
    "The prosign 'SK' (...-.-) means 'End of Contact' and is often sent as one continuous character.",
    "Morse code was officially replaced by the Global Maritime Distress and Safety System (GMDSS) in 1999 for sea communication.",
    "Despite being replaced for official maritime use, it's still a popular hobby among amateur radio operators.",
    "There are different versions of Morse code, such as American Morse and International Morse. International is the standard today.",
    "The 'Koch method' is another learning technique where you learn characters at full speed from the start.",
    "The theme song for the TV show 'Some Mothers Do 'Ave 'Em' spells out the show's title in Morse code.",
    "The word 'listen' contains the same letters as the word 'silent'.",
    "In Morse code, the longest character is the dollar sign '$' (...-..-).",
    "The numbers in Morse code were designed to be very distinct from letters to avoid confusion.",
    "A 'fist' in Morse code terminology refers to an operator's unique sending style, like handwriting.",
    "Before audio tones, telegraph operators listened to the 'click' and 'clack' of the receiver.",
    "The band Rush used Morse code for the letters 'YYZ' in their song of the same name, representing Toronto's airport code.",
    "Morse code can be sent very efficiently with very low power, making it great for long-distance contacts.",
    "The prosign 'CQ' (-.-.--.-) means 'Calling any station'.",
    "The number '73' is a common ham radio abbreviation for 'Best regards'.",
    "Morse code is considered the first digital code.",
    "Jeremiah Denton, a captured American pilot in Vietnam, blinked 'T-O-R-T-U-R-E' in Morse code during a televised interview.",
    "The equals sign '=' (-...-) is also known as the 'BT' prosign, used to separate parts of a message.",
    "International Morse code was created to handle accented characters in other languages.",
    "The punctuation mark for a comma (--) is longer than the period (.-.-.-).",
    "The question mark in Morse (..--..) sounds like 'didahdidah'.",
    "In the movie 'Independence Day', Morse code is used to coordinate a counterattack against the aliens.",
    "The @ symbol (.--.-.) was added to the Morse code chart in 2004.",
    "The exclamation point (-.-.--) was once represented by four dots.",
    "Sending Morse code with a straight key is an art form that requires a good sense of rhythm.",
    "Electronic 'keyers' can automatically generate perfectly timed dots and dashes.",
    "The song 'Radio Ga Ga' by Queen mentions 'through wars of worlds/invaded by Mars', a nod to the radio's history.",
    "The German military used a complex version of Morse code with their Enigma machines.",
    "The first transatlantic telegraph cable in 1858 connected Ireland and Newfoundland.",
    "The initial transatlantic cable failed after only three weeks of use.",
    "The word 'dah' is officially used by the International Telecommunication Union (ITU).",
    "The term 'dit' is more informal; the ITU's official term is 'unit'.",
    "The rhythm of Morse code is sometimes compared to music.",
    "In Japan, a variation called Wabun code is used to represent Japanese characters.",
    "There is no official Morse code for the underscore character '_', though '..--.-' is a common unofficial representation.",
    "A 'Q-code' is a three-letter code used in radio communication, like 'QTH' for 'What is your location?'.",
    "Learning Morse code can improve cognitive skills and memory.",
    "The phrase 'the quick brown fox jumps over the lazy dog' is a pangram used for practice as it contains every letter.",
    "A 'paddle' is a type of key that sends dots with one thumb and dashes with the other.",
    "A 'bug' key is a semi-automatic key that creates dots automatically but requires the operator to form the dashes manually.",
    "The 'Call of the S.O.S.' is a French film from 1928, showcasing the importance of the distress signal.",
    "The Boy Scouts of America still teach Morse code for a merit badge.",
    "The character 'AR' (.-.-.) is a prosign meaning 'End of message'.",
    "Some people practice Morse code by tapping their teeth together.",
    "The 'PARIS' method calculates WPM by timing how many times the word 'PARIS' can be sent in a minute.",
    "Morse code is still used by the U.S. Navy for signaling with lights between ships.",
    "The average word length in English is considered to be 5 characters for WPM calculations.",
    "The term 'ham radio' for amateur radio might have come from the station initials of early pioneers.",
    "Morse code doesn't distinguish between upper and lower case letters.",
    "A telegraph 'sounder' was the device that made the clicking noises operators would listen to.",
    "The theme for the TV series 'Sherlock' features Morse code tapping in its opening score.",
    "The phrase '...- / --' in Morse code spells out 'V M', representing Victory in Morse.",
    "The character for a plus sign '+' (.-.-.) is the same as the 'AR' prosign.",
    "The 'separator' prosign 'BT' (-...-) is used like a pause or a new paragraph.",
    "During the Cold War, 'numbers stations' would broadcast lists of numbers, often in Morse code, for spies.",
    "A 'Z-code' is another set of operating signals used in radio communication, like 'ZAP' for 'Acknowledge, please'.",
    "The first telegraph line in the U.S. stretched from Washington D.C. to Baltimore.",
    "The original American Morse code had different timings and more symbols than the International version.",
    "Sending 'HI HI' in Morse code is the equivalent of laughing.",
    "A semicolon in Morse is '-.-.-.'.",
    "The video game 'Outer Wilds' uses sound and light signals inspired by Morse code for communication.",
    "An 'elmer' in ham radio is a mentor who helps newcomers learn skills like Morse code.",
    "The sound of Morse code is often described as 'musical' by experienced operators.",
    "The letter 'L' (.-..) has a very distinct, lilting sound.",
    "The letter 'C' (-.-.) has a hard, syncopated rhythm.",
    "The speed of light made telegraphic communication seem instantaneous.",
    "The Apollo 11 mission's call signs 'Eagle' and 'Columbia' were confirmed using Morse code.",
    "The prosign 'AS' (.-...) means 'Wait'.",
    "The final Morse code message sent from the U.S. coast guard in 1995 was '...-.- ...-.- DE NCG SK', meaning 'End of Contact, out'.",
    "The 'V' signal (...-) was famously used by the BBC during WWII as a symbol of 'Victory'.",
    "The opening of Beethoven's 5th Symphony has a rhythm similar to the Morse letter 'V'.",
    "The prosign 'KA' (-.-.-) means 'Start of message'.",
    "Morse code is a powerful tool in emergency situations when other technologies fail."
];
